name: CI

on: [push, pull_request]

jobs:
  commitlint:                
    - name: lintcommit
      uses: remarkablemark/commitlint@v1.0.0

  build:
    needs: commitlint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        src: [ "src/main.c" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO examples
        run: pio ci --project-conf=platformio.ini
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.src }}